name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      CUDA_VISIBLE_DEVICES: ''  # Disable CUDA
      FORCE_CUDA: '0'          # Force CPU usage
      NO_CUDA: '1'            # Disable CUDA

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Force pip to install CPU-only versions
        export TORCH_CUDA_ARCH_LIST="None"
        pip install -r requirements.txt
    
    - name: Train model
      run: |
        python train.py
    
    - name: Run tests
      run: |
        python -m pytest test_model.py -v
    
    - name: Archive model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/
        retention-days: 90